export default function ShortlistedTermsPage() {
  return (
    <main className="min-h-screen bg-white flex flex-col">
      <header className="border-b border-gray-100 px-6 py-5">
        <div className="max-w-3xl mx-auto flex items-baseline gap-3">
          <a
            href="/shortlisted"
            className="text-2xl font-bold tracking-tight"
            style={{ fontFamily: "Georgia, serif", color: "inherit", textDecoration: "none" }}
          >
            Shortlisted
          </a>
        </div>
      </header>

      <div className="flex-1 max-w-3xl mx-auto w-full px-6 py-12">
        <h1
          className="text-3xl font-bold text-gray-900 mb-2"
          style={{ fontFamily: "Georgia, serif" }}
        >
          Terms &amp; Conditions
        </h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: April 2025</p>

        <div className="prose prose-gray max-w-none space-y-8 text-sm text-gray-700 leading-relaxed">

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">1. About this service</h2>
            <p>
              Shortlisted is an AI-powered UCAS personal statement review tool operated by GradeStack.
              It provides automated, AI-generated feedback on personal statements submitted by users.
              The service is not affiliated with UCAS or any UK university.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">2. Pricing</h2>
            <p>
              A free summary of your first criterion is provided at no charge. Full analysis — covering
              all five criteria, paragraph-by-paragraph annotations, and rewrite suggestions — is
              available for a one-time payment of <strong>£4.99</strong> (including VAT where applicable).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">3. No refund policy</h2>
            <p>
              Because Shortlisted delivers digital content that is made available immediately upon
              payment, you lose your statutory right to cancel under the Consumer Contracts Regulations
              2013 once the analysis has been delivered to you. By completing payment you confirm you
              consent to immediate delivery and acknowledge that the right of withdrawal does not apply.
            </p>
            <p className="mt-3">
              This does not affect your rights under the Consumer Rights Act 2015 if the service is
              faulty or not as described. If you believe your analysis was not delivered or was
              materially defective, contact us at{" "}
              <a href="mailto:results@gradestack.co.uk" className="text-[#C24E2A] underline">
                results@gradestack.co.uk
              </a>{" "}
              within 7 days and we will investigate.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">4. Data retention</h2>
            <p>
              Your personal statement and analysis results are stored for 48 hours from the time of
              submission, after which they are automatically and permanently deleted. We strongly
              recommend saving or downloading your results before the 48-hour window expires. We are
              unable to recover results after deletion.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">5. Nature of the analysis</h2>
            <p>
              The feedback provided by Shortlisted is generated by an AI model and is intended as a
              study aid only. It does not constitute professional admissions advice and does not
              guarantee admission to any university. GradeStack accepts no responsibility for
              decisions made in reliance on the analysis.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">6. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Submit content that is defamatory, unlawful, or harmful.</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the service.</li>
              <li>Use automated tools to submit statements in bulk.</li>
            </ul>
            <p className="mt-3">
              We reserve the right to suspend access to users who breach these terms without notice
              or refund.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">7. Limitation of liability</h2>
            <p>
              To the fullest extent permitted by law, GradeStack&apos;s total liability to you in
              connection with Shortlisted shall not exceed the amount you paid for the analysis
              (£4.99). We are not liable for any indirect, consequential, or special losses,
              including loss of university place or opportunity.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">8. Governing law</h2>
            <p>
              These terms are governed by the laws of England and Wales. Any disputes shall be
              subject to the exclusive jurisdiction of the courts of England and Wales.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">9. Contact</h2>
            <p>
              For any queries regarding these terms, contact us at{" "}
              <a href="mailto:results@gradestack.co.uk" className="text-[#C24E2A] underline">
                results@gradestack.co.uk
              </a>.
            </p>
          </section>

        </div>
      </div>

      <footer className="border-t border-gray-100 px-6 py-5 text-center text-xs text-gray-400">
        <p>
          <a href="/shortlisted/privacy" className="hover:text-gray-600 transition">Privacy Policy</a>
          {" · "}
          <a href="/shortlisted/terms" className="hover:text-gray-600 transition">Terms &amp; Conditions</a>
          {" · "}
          &copy; 2026 Shortlisted
        </p>
      </footer>
    </main>
  );
}
