// ============================================================
// TYPES — Pointwise Tariff System
// ============================================================

export type QualType =
  | 'a-level'
  | 'as-level'
  | 'epq'
  | 'core-maths'
  | 'btec'
  | 'cambridge-technical'
  | 't-level'
  | 'ib-diploma'
  | 'ib-subject-hl'
  | 'ib-subject-sl'
  | 'scottish-higher'
  | 'scottish-advanced-higher'
  | 'cambridge-pre-u'
  | 'cambridge-pre-u-gpr'
  | 'music-grade'
  | 'welsh-bacc'
  | 'access-to-he'
  | 'other'

// What the AI parsing layer returns — deliberately loose,
// because humans are imprecise. Deterministic layer cleans it up.
export interface ParsedQualification {
  type: QualType
  grade: string               // Raw grade string: 'A*', 'D*D*D', 'Merit', '7', etc.
  subject?: string            // 'Mathematics', 'Biology', 'Piano' (for music)
  awarding_body?: string      // 'ABRSM', 'Trinity', 'Pearson', 'AQA', etc.
  size?: string               // BTEC size: 'Extended Diploma', 'Diploma', etc.
  music_grade_number?: number // 6, 7, or 8 — only for music-grade type
  ib_score?: number           // 24–45 — only for ib-diploma
  raw: string                 // Exact original text that was parsed
  confidence: 'high' | 'medium' | 'low'
  needs_clarification?: string // Human-readable question if ambiguous
}

// What the deterministic lookup layer returns
export interface ResolvedQualification extends ParsedQualification {
  points: number
  display_name: string
  tariff_entry_id: string
  lookup_status: 'found' | 'not_in_tariff' | 'ambiguous' | 'error'
  lookup_note?: string  // e.g. "Grade 5 piano doesn't attract UCAS points"
  excluded?: boolean
  excluded_reason?: string
}

// Final result object for a user's full qualification set
export interface TariffResult {
  qualifications: ResolvedQualification[]
  total_points: number
  rules_applied: AppliedRule[]
  warnings: string[]  // e.g. "Only your best 3 A-levels have been counted"
  context: TariffContext
  generated_at: string // ISO timestamp
}

export interface AppliedRule {
  rule_key: string
  affected_quals: string[]  // raw strings of quals affected
  points_removed: number
  explanation: string
}

// Contextual framing generated by AI — not deterministic
export interface TariffContext {
  summary: string          // "You have 152 UCAS points..."
  tier_label: string       // "Russell Group range", "Post-92 competitive", etc.
  tier_description: string // Longer explanation of what this means
  quick_wins: QuickWin[]   // Optimisation suggestions
}

export interface QuickWin {
  title: string
  description: string
  points_gain: number
  qualification_type: QualType
}

// For the scenario planner — user edits qualifications and we recalculate
export interface ScenarioEdit {
  original: ParsedQualification
  edited: ParsedQualification
  delta_points: number // positive = improvement
}

// API request/response shapes
export interface ParseRequest {
  input: string  // Raw user text
  session_id?: string
}

export interface ParseResponse {
  parsed: ParsedQualification[]
  ambiguities: string[]  // Qualifications we couldn't confidently parse
  raw_input: string
}

export interface CalculateRequest {
  qualifications: ParsedQualification[]
  scenario_mode?: boolean  // If true, don't apply default A-level max_count rule
}

export interface CalculateResponse {
  result: TariffResult
}
