export const UNIVERSITIES = [
  {
    name: "University of Oxford",
    city: "Oxford",
    courses: [
      { name: "Medicine", min_points: 216, typical_points: 228, url: "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/medicine" },
      { name: "Law", min_points: 216, typical_points: 228, url: "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/jurisprudence" },
      { name: "Computer Science", min_points: 216, typical_points: 228, url: "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/computer-science" },
      { name: "Economics", min_points: 216, typical_points: 228, url: "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/economics-and-management" },
      { name: "History", min_points: 216, typical_points: 228, url: "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/history" },
      { name: "English", min_points: 216, typical_points: 228, url: "https://www.ox.ac.uk/admissions/undergraduate/courses/course-listing/english-language-and-literature" },
    ],
  },
  {
    name: "University of Cambridge",
    city: "Cambridge",
    courses: [
      { name: "Medicine", min_points: 216, typical_points: 228, url: "https://www.undergraduate.study.cam.ac.uk/courses/medicine" },
      { name: "Law", min_points: 216, typical_points: 228, url: "https://www.undergraduate.study.cam.ac.uk/courses/law" },
      { name: "Engineering", min_points: 212, typical_points: 228, url: "https://www.undergraduate.study.cam.ac.uk/courses/engineering" },
      { name: "Computer Science", min_points: 212, typical_points: 228, url: "https://www.undergraduate.study.cam.ac.uk/courses/computer-science" },
      { name: "Economics", min_points: 216, typical_points: 228, url: "https://www.undergraduate.study.cam.ac.uk/courses/economics" },
      { name: "History", min_points: 216, typical_points: 228, url: "https://www.undergraduate.study.cam.ac.uk/courses/history" },
      { name: "English", min_points: 216, typical_points: 228, url: "https://www.undergraduate.study.cam.ac.uk/courses/english" },
      { name: "Biology", min_points: 212, typical_points: 228, url: "https://www.undergraduate.study.cam.ac.uk/courses/natural-sciences" },
      { name: "Chemistry", min_points: 212, typical_points: 228, url: "https://www.undergraduate.study.cam.ac.uk/courses/natural-sciences" },
    ],
  },
  {
    name: "Imperial College London",
    city: "London",
    courses: [
      { name: "Medicine", min_points: 200, typical_points: 216, url: "https://www.imperial.ac.uk/study/courses/undergraduate/medicine/" },
      { name: "Engineering", min_points: 192, typical_points: 210, url: "https://www.imperial.ac.uk/study/courses/undergraduate/electrical-electronic-engineering/" },
      { name: "Computer Science", min_points: 192, typical_points: 210, url: "https://www.imperial.ac.uk/study/courses/undergraduate/computing/" },
      { name: "Chemistry", min_points: 192, typical_points: 210, url: "https://www.imperial.ac.uk/study/courses/undergraduate/chemistry/" },
      { name: "Biology", min_points: 192, typical_points: 208, url: "https://www.imperial.ac.uk/study/courses/undergraduate/biochemistry/" },
    ],
  },
  {
    name: "London School of Economics",
    city: "London",
    courses: [
      { name: "Economics", min_points: 192, typical_points: 216, url: "https://www.lse.ac.uk/study-at-lse/Undergraduate/degree-programmes/BSc-Economics" },
      { name: "Law", min_points: 192, typical_points: 216, url: "https://www.lse.ac.uk/study-at-lse/Undergraduate/degree-programmes/LLB-Laws" },
      { name: "History", min_points: 185, typical_points: 208, url: "https://www.lse.ac.uk/study-at-lse/Undergraduate/degree-programmes/BSc-Economic-History" },
      { name: "Psychology", min_points: 185, typical_points: 208, url: "https://www.lse.ac.uk/study-at-lse/Undergraduate/degree-programmes/BSc-Psychological-and-Behavioural-Science" },
    ],
  },
  {
    name: "University College London",
    city: "London",
    courses: [
      { name: "Medicine", min_points: 200, typical_points: 216, url: "https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/medicine-mbbs" },
      { name: "Law", min_points: 192, typical_points: 210, url: "https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/law-llb" },
      { name: "Engineering", min_points: 185, typical_points: 204, url: "https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/engineering" },
      { name: "Computer Science", min_points: 185, typical_points: 204, url: "https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/computer-science-bsc" },
      { name: "Economics", min_points: 185, typical_points: 208, url: "https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/economics-bsc" },
      { name: "Psychology", min_points: 176, typical_points: 196, url: "https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/psychology-bsc" },
      { name: "English", min_points: 176, typical_points: 196, url: "https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/english-ba" },
      { name: "History", min_points: 176, typical_points: 196, url: "https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/history-ba" },
    ],
  },
  {
    name: "University of Edinburgh",
    city: "Edinburgh",
    courses: [
      { name: "Medicine", min_points: 176, typical_points: 204, url: "https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=view&code=A100" },
      { name: "Law", min_points: 176, typical_points: 196, url: "https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=view&code=M100" },
      { name: "Computer Science", min_points: 152, typical_points: 176, url: "https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=view&code=GG14" },
      { name: "Engineering", min_points: 152, typical_points: 176, url: "https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=view&code=H100" },
      { name: "Economics", min_points: 152, typical_points: 176, url: "https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=view&code=L100" },
      { name: "Psychology", min_points: 144, typical_points: 168, url: "https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=view&code=C800" },
      { name: "English", min_points: 152, typical_points: 168, url: "https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=view&code=Q300" },
      { name: "History", min_points: 144, typical_points: 168, url: "https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=view&code=V100" },
      { name: "Biology", min_points: 144, typical_points: 168, url: "https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=view&code=C100" },
      { name: "Chemistry", min_points: 152, typical_points: 176, url: "https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=view&code=F100" },
    ],
  },
  {
    name: "University of Manchester",
    city: "Manchester",
    courses: [
      { name: "Medicine", min_points: 176, typical_points: 200, url: "https://www.manchester.ac.uk/study/undergraduate/courses/2025/00569/mbchb-medicine/" },
      { name: "Law", min_points: 152, typical_points: 176, url: "https://www.manchester.ac.uk/study/undergraduate/courses/2025/00584/llb-law/" },
      { name: "Engineering", min_points: 144, typical_points: 168, url: "https://www.manchester.ac.uk/study/undergraduate/courses/2025/00557/beng-mechanical-engineering/" },
      { name: "Computer Science", min_points: 144, typical_points: 168, url: "https://www.manchester.ac.uk/study/undergraduate/courses/2025/00522/bsc-computer-science/" },
      { name: "Economics", min_points: 144, typical_points: 168, url: "https://www.manchester.ac.uk/study/undergraduate/courses/2025/00534/bsc-economics/" },
      { name: "Psychology", min_points: 136, typical_points: 160, url: "https://www.manchester.ac.uk/study/undergraduate/courses/2025/00603/bsc-psychology/" },
      { name: "History", min_points: 136, typical_points: 160, url: "https://www.manchester.ac.uk/study/undergraduate/courses/2025/00566/ba-history/" },
      { name: "Biology", min_points: 136, typical_points: 160, url: "https://www.manchester.ac.uk/study/undergraduate/courses/2025/00512/bsc-biology/" },
      { name: "Chemistry", min_points: 136, typical_points: 160, url: "https://www.manchester.ac.uk/study/undergraduate/courses/2025/00520/bsc-chemistry/" },
    ],
  },
  {
    name: "King's College London",
    city: "London",
    courses: [
      { name: "Medicine", min_points: 192, typical_points: 216, url: "https://www.kcl.ac.uk/study/undergraduate/courses/medicine-mbbs" },
      { name: "Law", min_points: 176, typical_points: 200, url: "https://www.kcl.ac.uk/study/undergraduate/courses/law-llb" },
      { name: "Computer Science", min_points: 152, typical_points: 176, url: "https://www.kcl.ac.uk/study/undergraduate/courses/computer-science-bsc" },
      { name: "Economics", min_points: 160, typical_points: 184, url: "https://www.kcl.ac.uk/study/undergraduate/courses/economics-bsc" },
      { name: "Psychology", min_points: 152, typical_points: 176, url: "https://www.kcl.ac.uk/study/undergraduate/courses/psychology-bsc" },
      { name: "English", min_points: 144, typical_points: 168, url: "https://www.kcl.ac.uk/study/undergraduate/courses/english-language-and-linguistics-ba" },
      { name: "History", min_points: 144, typical_points: 168, url: "https://www.kcl.ac.uk/study/undergraduate/courses/history-ba" },
    ],
  },
  {
    name: "University of Bristol",
    city: "Bristol",
    courses: [
      { name: "Medicine", min_points: 176, typical_points: 200, url: "https://www.bristol.ac.uk/study/undergraduate/2025/medicine/mbchb-medicine/" },
      { name: "Law", min_points: 152, typical_points: 176, url: "https://www.bristol.ac.uk/study/undergraduate/2025/law/llb-law/" },
      { name: "Engineering", min_points: 144, typical_points: 168, url: "https://www.bristol.ac.uk/study/undergraduate/2025/engineering/beng-engineering/" },
      { name: "Computer Science", min_points: 144, typical_points: 168, url: "https://www.bristol.ac.uk/study/undergraduate/2025/computer-science/bsc-computer-science/" },
      { name: "Economics", min_points: 152, typical_points: 176, url: "https://www.bristol.ac.uk/study/undergraduate/2025/economics/bsc-economics/" },
      { name: "Psychology", min_points: 136, typical_points: 160, url: "https://www.bristol.ac.uk/study/undergraduate/2025/psychology/bsc-psychology/" },
      { name: "English", min_points: 136, typical_points: 160, url: "https://www.bristol.ac.uk/study/undergraduate/2025/english/ba-english/" },
      { name: "Chemistry", min_points: 136, typical_points: 160, url: "https://www.bristol.ac.uk/study/undergraduate/2025/chemistry/bsc-chemistry/" },
    ],
  },
  {
    name: "University of Warwick",
    city: "Coventry",
    courses: [
      { name: "Medicine", min_points: 192, typical_points: 216, url: "https://warwick.ac.uk/study/undergraduate/courses/medicine/" },
      { name: "Law", min_points: 160, typical_points: 184, url: "https://warwick.ac.uk/study/undergraduate/courses/law/" },
      { name: "Engineering", min_points: 144, typical_points: 168, url: "https://warwick.ac.uk/study/undergraduate/courses/engineering/" },
      { name: "Computer Science", min_points: 152, typical_points: 176, url: "https://warwick.ac.uk/study/undergraduate/courses/computerscience/" },
      { name: "Economics", min_points: 160, typical_points: 184, url: "https://warwick.ac.uk/study/undergraduate/courses/economics/" },
      { name: "History", min_points: 136, typical_points: 160, url: "https://warwick.ac.uk/study/undergraduate/courses/history/" },
      { name: "Psychology", min_points: 136, typical_points: 160, url: "https://warwick.ac.uk/study/undergraduate/courses/psychology/" },
    ],
  },
  {
    name: "University of Glasgow",
    city: "Glasgow",
    courses: [
      { name: "Medicine", min_points: 168, typical_points: 192, url: "https://www.gla.ac.uk/undergraduate/degrees/medicine/" },
      { name: "Law", min_points: 152, typical_points: 168, url: "https://www.gla.ac.uk/undergraduate/degrees/law/" },
      { name: "Engineering", min_points: 136, typical_points: 152, url: "https://www.gla.ac.uk/undergraduate/degrees/electronicselectricalengineering/" },
      { name: "Computer Science", min_points: 136, typical_points: 152, url: "https://www.gla.ac.uk/undergraduate/degrees/computingscience/" },
      { name: "Economics", min_points: 136, typical_points: 152, url: "https://www.gla.ac.uk/undergraduate/degrees/economics/" },
      { name: "Psychology", min_points: 128, typical_points: 144, url: "https://www.gla.ac.uk/undergraduate/degrees/psychology/" },
      { name: "History", min_points: 120, typical_points: 136, url: "https://www.gla.ac.uk/undergraduate/degrees/history/" },
    ],
  },
  {
    name: "University of Birmingham",
    city: "Birmingham",
    courses: [
      { name: "Medicine", min_points: 168, typical_points: 192, url: "https://www.birmingham.ac.uk/undergraduate/courses/med/medicine.aspx" },
      { name: "Law", min_points: 144, typical_points: 168, url: "https://www.birmingham.ac.uk/undergraduate/courses/law/law.aspx" },
      { name: "Engineering", min_points: 128, typical_points: 152, url: "https://www.birmingham.ac.uk/undergraduate/courses/eese/engineering-beng.aspx" },
      { name: "Computer Science", min_points: 128, typical_points: 152, url: "https://www.birmingham.ac.uk/undergraduate/courses/cs/computer-science.aspx" },
      { name: "Economics", min_points: 136, typical_points: 160, url: "https://www.birmingham.ac.uk/undergraduate/courses/econ/economics.aspx" },
      { name: "Psychology", min_points: 128, typical_points: 152, url: "https://www.birmingham.ac.uk/undergraduate/courses/psych/psychology.aspx" },
      { name: "English", min_points: 128, typical_points: 144, url: "https://www.birmingham.ac.uk/undergraduate/courses/engl/english-literature.aspx" },
    ],
  },
  {
    name: "University of Leeds",
    city: "Leeds",
    courses: [
      { name: "Medicine", min_points: 168, typical_points: 192, url: "https://courses.leeds.ac.uk/g998/medicine-mbchb" },
      { name: "Law", min_points: 144, typical_points: 168, url: "https://courses.leeds.ac.uk/m100/law-llb" },
      { name: "Engineering", min_points: 128, typical_points: 152, url: "https://courses.leeds.ac.uk/h300/mechanical-engineering-beng" },
      { name: "Computer Science", min_points: 128, typical_points: 152, url: "https://courses.leeds.ac.uk/g400/computer-science-bsc" },
      { name: "Economics", min_points: 128, typical_points: 152, url: "https://courses.leeds.ac.uk/l100/economics-bsc" },
      { name: "Psychology", min_points: 120, typical_points: 144, url: "https://courses.leeds.ac.uk/c800/psychology-bsc" },
      { name: "History", min_points: 120, typical_points: 136, url: "https://courses.leeds.ac.uk/v100/history-ba" },
      { name: "Biology", min_points: 120, typical_points: 144, url: "https://courses.leeds.ac.uk/c100/biology-bsc" },
    ],
  },
  {
    name: "University of Sheffield",
    city: "Sheffield",
    courses: [
      { name: "Medicine", min_points: 168, typical_points: 192, url: "https://www.sheffield.ac.uk/medicine/undergraduate-courses/mbchb-medicine" },
      { name: "Law", min_points: 136, typical_points: 160, url: "https://www.sheffield.ac.uk/law/undergraduate" },
      { name: "Engineering", min_points: 128, typical_points: 152, url: "https://www.sheffield.ac.uk/mecheng/undergraduate" },
      { name: "Computer Science", min_points: 128, typical_points: 152, url: "https://www.sheffield.ac.uk/dcs/undergraduate" },
      { name: "Economics", min_points: 120, typical_points: 144, url: "https://www.sheffield.ac.uk/economics/undergraduate" },
      { name: "Psychology", min_points: 120, typical_points: 136, url: "https://www.sheffield.ac.uk/psychology/undergraduate" },
      { name: "Chemistry", min_points: 120, typical_points: 144, url: "https://www.sheffield.ac.uk/chemistry/undergraduate" },
    ],
  },
  {
    name: "University of Nottingham",
    city: "Nottingham",
    courses: [
      { name: "Medicine", min_points: 168, typical_points: 192, url: "https://www.nottingham.ac.uk/ugstudy/courses/medicine/medicine-bmbs.aspx" },
      { name: "Law", min_points: 136, typical_points: 160, url: "https://www.nottingham.ac.uk/ugstudy/courses/law/law.aspx" },
      { name: "Engineering", min_points: 128, typical_points: 152, url: "https://www.nottingham.ac.uk/ugstudy/courses/engineering/mechanical-engineering-beng.aspx" },
      { name: "Computer Science", min_points: 128, typical_points: 152, url: "https://www.nottingham.ac.uk/ugstudy/courses/computer-science/computer-science-bsc.aspx" },
      { name: "Economics", min_points: 128, typical_points: 152, url: "https://www.nottingham.ac.uk/ugstudy/courses/economics/economics-bsc.aspx" },
      { name: "Psychology", min_points: 120, typical_points: 144, url: "https://www.nottingham.ac.uk/ugstudy/courses/psychology/psychology-bsc.aspx" },
      { name: "Biology", min_points: 120, typical_points: 144, url: "https://www.nottingham.ac.uk/ugstudy/courses/life-sciences/biology-bsc.aspx" },
    ],
  },
  {
    name: "Durham University",
    city: "Durham",
    courses: [
      { name: "Law", min_points: 168, typical_points: 192, url: "https://www.durham.ac.uk/study/undergraduate/law-llb/" },
      { name: "Economics", min_points: 160, typical_points: 184, url: "https://www.durham.ac.uk/study/undergraduate/economics-bsc/" },
      { name: "Computer Science", min_points: 152, typical_points: 176, url: "https://www.durham.ac.uk/study/undergraduate/computer-science-bsc/" },
      { name: "Engineering", min_points: 152, typical_points: 176, url: "https://www.durham.ac.uk/study/undergraduate/engineering-beng/" },
      { name: "Psychology", min_points: 144, typical_points: 168, url: "https://www.durham.ac.uk/study/undergraduate/psychology-bsc/" },
      { name: "English", min_points: 144, typical_points: 168, url: "https://www.durham.ac.uk/study/undergraduate/english-literature-ba/" },
      { name: "History", min_points: 144, typical_points: 168, url: "https://www.durham.ac.uk/study/undergraduate/history-ba/" },
      { name: "Chemistry", min_points: 144, typical_points: 168, url: "https://www.durham.ac.uk/study/undergraduate/chemistry-bsc/" },
    ],
  },
  {
    name: "University of Southampton",
    city: "Southampton",
    courses: [
      { name: "Medicine", min_points: 160, typical_points: 184, url: "https://www.southampton.ac.uk/courses/medicine-degree-bmbs" },
      { name: "Engineering", min_points: 128, typical_points: 152, url: "https://www.southampton.ac.uk/courses/mechanical-engineering-degree-beng" },
      { name: "Computer Science", min_points: 128, typical_points: 152, url: "https://www.southampton.ac.uk/courses/computer-science-degree-bsc" },
      { name: "Economics", min_points: 128, typical_points: 152, url: "https://www.southampton.ac.uk/courses/economics-degree-bsc" },
      { name: "Psychology", min_points: 120, typical_points: 136, url: "https://www.southampton.ac.uk/courses/psychology-degree-bsc" },
      { name: "Biology", min_points: 120, typical_points: 136, url: "https://www.southampton.ac.uk/courses/biology-degree-bsc" },
    ],
  },
  {
    name: "Newcastle University",
    city: "Newcastle",
    courses: [
      { name: "Medicine", min_points: 160, typical_points: 184, url: "https://www.ncl.ac.uk/undergraduate/degrees/a100/" },
      { name: "Law", min_points: 136, typical_points: 160, url: "https://www.ncl.ac.uk/undergraduate/degrees/m100/" },
      { name: "Engineering", min_points: 120, typical_points: 144, url: "https://www.ncl.ac.uk/undergraduate/degrees/h300/" },
      { name: "Computer Science", min_points: 120, typical_points: 144, url: "https://www.ncl.ac.uk/undergraduate/degrees/g400/" },
      { name: "Psychology", min_points: 112, typical_points: 128, url: "https://www.ncl.ac.uk/undergraduate/degrees/c800/" },
      { name: "History", min_points: 112, typical_points: 128, url: "https://www.ncl.ac.uk/undergraduate/degrees/v100/" },
    ],
  },
  {
    name: "Queen Mary University of London",
    city: "London",
    courses: [
      { name: "Medicine", min_points: 168, typical_points: 192, url: "https://www.qmul.ac.uk/undergraduate/coursefinder/courses/medicine-mbbs/" },
      { name: "Law", min_points: 136, typical_points: 160, url: "https://www.qmul.ac.uk/undergraduate/coursefinder/courses/law-llb/" },
      { name: "Computer Science", min_points: 128, typical_points: 152, url: "https://www.qmul.ac.uk/undergraduate/coursefinder/courses/computer-science-bsc/" },
      { name: "Economics", min_points: 128, typical_points: 152, url: "https://www.qmul.ac.uk/undergraduate/coursefinder/courses/economics-bsc/" },
      { name: "History", min_points: 112, typical_points: 128, url: "https://www.qmul.ac.uk/undergraduate/coursefinder/courses/history-ba/" },
      { name: "English", min_points: 112, typical_points: 128, url: "https://www.qmul.ac.uk/undergraduate/coursefinder/courses/english-ba/" },
    ],
  },
  {
    name: "University of Liverpool",
    city: "Liverpool",
    courses: [
      { name: "Medicine", min_points: 160, typical_points: 184, url: "https://www.liverpool.ac.uk/study/undergraduate/courses/medicine-mbchb/overview/" },
      { name: "Law", min_points: 128, typical_points: 152, url: "https://www.liverpool.ac.uk/study/undergraduate/courses/law-llb/overview/" },
      { name: "Engineering", min_points: 112, typical_points: 136, url: "https://www.liverpool.ac.uk/study/undergraduate/courses/mechanical-engineering-beng/overview/" },
      { name: "Computer Science", min_points: 112, typical_points: 136, url: "https://www.liverpool.ac.uk/study/undergraduate/courses/computer-science-bsc/overview/" },
      { name: "Economics", min_points: 112, typical_points: 128, url: "https://www.liverpool.ac.uk/study/undergraduate/courses/economics-bsc/overview/" },
      { name: "Psychology", min_points: 112, typical_points: 128, url: "https://www.liverpool.ac.uk/study/undergraduate/courses/psychology-bsc/overview/" },
    ],
  },
  {
    name: "University of Exeter",
    city: "Exeter",
    courses: [
      { name: "Law", min_points: 144, typical_points: 168, url: "https://www.exeter.ac.uk/undergraduate/degrees/law/law/" },
      { name: "Economics", min_points: 144, typical_points: 168, url: "https://www.exeter.ac.uk/undergraduate/degrees/economics/economics/" },
      { name: "Computer Science", min_points: 128, typical_points: 152, url: "https://www.exeter.ac.uk/undergraduate/degrees/computerscience/computer-science/" },
      { name: "Psychology", min_points: 128, typical_points: 144, url: "https://www.exeter.ac.uk/undergraduate/degrees/psychology/psychology/" },
      { name: "English", min_points: 120, typical_points: 136, url: "https://www.exeter.ac.uk/undergraduate/degrees/english/english/" },
      { name: "History", min_points: 120, typical_points: 136, url: "https://www.exeter.ac.uk/undergraduate/degrees/history/history/" },
      { name: "Biology", min_points: 120, typical_points: 136, url: "https://www.exeter.ac.uk/undergraduate/degrees/biosciences/biology/" },
    ],
  },
  {
    name: "University of St Andrews",
    city: "St Andrews",
    courses: [
      { name: "Medicine", min_points: 176, typical_points: 200, url: "https://www.st-andrews.ac.uk/subjects/medicine/medicine-bsc-hons/" },
      { name: "Computer Science", min_points: 152, typical_points: 176, url: "https://www.st-andrews.ac.uk/subjects/computer-science/computer-science-bsc-hons/" },
      { name: "Economics", min_points: 152, typical_points: 176, url: "https://www.st-andrews.ac.uk/subjects/economics/economics-bsc-hons/" },
      { name: "Psychology", min_points: 136, typical_points: 160, url: "https://www.st-andrews.ac.uk/subjects/psychology/psychology-bsc-hons/" },
      { name: "English", min_points: 136, typical_points: 160, url: "https://www.st-andrews.ac.uk/subjects/english/english-ma-hons/" },
      { name: "History", min_points: 136, typical_points: 160, url: "https://www.st-andrews.ac.uk/subjects/history/history-ma-hons/" },
      { name: "Chemistry", min_points: 136, typical_points: 160, url: "https://www.st-andrews.ac.uk/subjects/chemistry/chemistry-bsc-hons/" },
    ],
  },
  {
    name: "Cardiff University",
    city: "Cardiff",
    courses: [
      { name: "Medicine", min_points: 160, typical_points: 184, url: "https://www.cardiff.ac.uk/study/undergraduate/courses/course/medicine-mbbch" },
      { name: "Law", min_points: 128, typical_points: 152, url: "https://www.cardiff.ac.uk/study/undergraduate/courses/course/law-llb" },
      { name: "Engineering", min_points: 112, typical_points: 128, url: "https://www.cardiff.ac.uk/study/undergraduate/courses/course/mechanical-engineering-beng" },
      { name: "Computer Science", min_points: 112, typical_points: 128, url: "https://www.cardiff.ac.uk/study/undergraduate/courses/course/computer-science-bsc" },
      { name: "Psychology", min_points: 104, typical_points: 120, url: "https://www.cardiff.ac.uk/study/undergraduate/courses/course/psychology-bsc" },
      { name: "English", min_points: 104, typical_points: 120, url: "https://www.cardiff.ac.uk/study/undergraduate/courses/course/english-literature-ba" },
      { name: "History", min_points: 104, typical_points: 120, url: "https://www.cardiff.ac.uk/study/undergraduate/courses/course/history-ba" },
    ],
  },
  {
    name: "Queen's University Belfast",
    city: "Belfast",
    courses: [
      { name: "Medicine", min_points: 160, typical_points: 184, url: "https://www.qub.ac.uk/courses/undergraduate/medicine-mb-bch-bao/A100/" },
      { name: "Law", min_points: 120, typical_points: 144, url: "https://www.qub.ac.uk/courses/undergraduate/law-llb/M100/" },
      { name: "Engineering", min_points: 104, typical_points: 120, url: "https://www.qub.ac.uk/courses/undergraduate/mechanical-and-aerospace-engineering-beng/H340/" },
      { name: "Computer Science", min_points: 104, typical_points: 120, url: "https://www.qub.ac.uk/courses/undergraduate/computer-science-bsc/G400/" },
      { name: "Psychology", min_points: 96, typical_points: 112, url: "https://www.qub.ac.uk/courses/undergraduate/psychology-bsc/C800/" },
    ],
  },
  {
    name: "University of Leicester",
    city: "Leicester",
    courses: [
      { name: "Medicine", min_points: 152, typical_points: 176, url: "https://le.ac.uk/courses/medicine-mbchb" },
      { name: "Law", min_points: 120, typical_points: 136, url: "https://le.ac.uk/courses/law-llb" },
      { name: "Engineering", min_points: 104, typical_points: 120, url: "https://le.ac.uk/courses/engineering-beng" },
      { name: "Computer Science", min_points: 104, typical_points: 120, url: "https://le.ac.uk/courses/computer-science-bsc" },
      { name: "Psychology", min_points: 104, typical_points: 120, url: "https://le.ac.uk/courses/psychology-bsc" },
      { name: "History", min_points: 96, typical_points: 112, url: "https://le.ac.uk/courses/history-ba" },
    ],
  },
  {
    name: "University of Reading",
    city: "Reading",
    courses: [
      { name: "Law", min_points: 112, typical_points: 128, url: "https://www.reading.ac.uk/law/undergraduate/llb-law" },
      { name: "Economics", min_points: 112, typical_points: 128, url: "https://www.reading.ac.uk/economics/undergraduate/bsc-economics" },
      { name: "Psychology", min_points: 104, typical_points: 120, url: "https://www.reading.ac.uk/psychology/undergraduate/bsc-psychology" },
      { name: "English", min_points: 104, typical_points: 112, url: "https://www.reading.ac.uk/english/undergraduate/ba-english-literature" },
      { name: "History", min_points: 96, typical_points: 112, url: "https://www.reading.ac.uk/history/undergraduate/ba-history" },
      { name: "Biology", min_points: 104, typical_points: 120, url: "https://www.reading.ac.uk/biology/undergraduate/bsc-biology" },
      { name: "Chemistry", min_points: 104, typical_points: 120, url: "https://www.reading.ac.uk/chemistry/undergraduate/bsc-chemistry" },
    ],
  },
  {
    name: "University of Surrey",
    city: "Guildford",
    courses: [
      { name: "Engineering", min_points: 112, typical_points: 128, url: "https://www.surrey.ac.uk/undergraduate/mechanical-engineering" },
      { name: "Computer Science", min_points: 112, typical_points: 128, url: "https://www.surrey.ac.uk/undergraduate/computer-science" },
      { name: "Economics", min_points: 112, typical_points: 128, url: "https://www.surrey.ac.uk/undergraduate/economics" },
      { name: "Psychology", min_points: 112, typical_points: 128, url: "https://www.surrey.ac.uk/undergraduate/psychology" },
    ],
  },
  {
    name: "Loughborough University",
    city: "Loughborough",
    courses: [
      { name: "Engineering", min_points: 128, typical_points: 152, url: "https://www.lboro.ac.uk/study/undergraduate/courses/mechanical-engineering-beng/" },
      { name: "Computer Science", min_points: 120, typical_points: 136, url: "https://www.lboro.ac.uk/study/undergraduate/courses/computer-science-bsc/" },
      { name: "Economics", min_points: 120, typical_points: 136, url: "https://www.lboro.ac.uk/study/undergraduate/courses/economics-bsc/" },
      { name: "Psychology", min_points: 112, typical_points: 128, url: "https://www.lboro.ac.uk/study/undergraduate/courses/psychology-bsc/" },
    ],
  },
  {
    name: "University of Bath",
    city: "Bath",
    courses: [
      { name: "Engineering", min_points: 152, typical_points: 176, url: "https://www.bath.ac.uk/courses/undergraduate/2025/mechanical-engineering/mechanical-engineering-beng/" },
      { name: "Computer Science", min_points: 144, typical_points: 168, url: "https://www.bath.ac.uk/courses/undergraduate/2025/computer-science/computer-science-bsc/" },
      { name: "Economics", min_points: 152, typical_points: 176, url: "https://www.bath.ac.uk/courses/undergraduate/2025/economics/economics-bsc/" },
      { name: "Psychology", min_points: 136, typical_points: 152, url: "https://www.bath.ac.uk/courses/undergraduate/2025/psychology/psychology-bsc/" },
    ],
  },
  {
    name: "University of York",
    city: "York",
    courses: [
      { name: "Law", min_points: 128, typical_points: 152, url: "https://www.york.ac.uk/law/undergraduate/courses/llb-law/" },
      { name: "Computer Science", min_points: 120, typical_points: 136, url: "https://www.york.ac.uk/computer-science/undergraduate/courses/bsc-computer-science/" },
      { name: "Economics", min_points: 120, typical_points: 136, url: "https://www.york.ac.uk/economics/undergraduate/courses/bsc-economics/" },
      { name: "Psychology", min_points: 112, typical_points: 128, url: "https://www.york.ac.uk/psychology/undergraduate/courses/bsc-psychology/" },
      { name: "English", min_points: 112, typical_points: 128, url: "https://www.york.ac.uk/english/undergraduate/courses/ba-english/" },
      { name: "History", min_points: 112, typical_points: 128, url: "https://www.york.ac.uk/history/undergraduate/courses/ba-history/" },
      { name: "Biology", min_points: 112, typical_points: 128, url: "https://www.york.ac.uk/biology/undergraduate/courses/bsc-biology/" },
    ],
  },
  {
    name: "University of East Anglia",
    city: "Norwich",
    courses: [
      { name: "Medicine", min_points: 144, typical_points: 168, url: "https://www.uea.ac.uk/course/undergraduate/medicine" },
      { name: "Law", min_points: 104, typical_points: 120, url: "https://www.uea.ac.uk/course/undergraduate/law-llb" },
      { name: "Economics", min_points: 104, typical_points: 120, url: "https://www.uea.ac.uk/course/undergraduate/economics" },
      { name: "Psychology", min_points: 104, typical_points: 120, url: "https://www.uea.ac.uk/course/undergraduate/psychology-bsc" },
      { name: "English", min_points: 96, typical_points: 112, url: "https://www.uea.ac.uk/course/undergraduate/english-literature-ba" },
      { name: "Biology", min_points: 104, typical_points: 120, url: "https://www.uea.ac.uk/course/undergraduate/biology-bsc" },
    ],
  },
  {
    name: "University of Sussex",
    city: "Brighton",
    courses: [
      { name: "Law", min_points: 104, typical_points: 120, url: "https://www.sussex.ac.uk/study/undergraduate/courses/law-llb" },
      { name: "Economics", min_points: 104, typical_points: 120, url: "https://www.sussex.ac.uk/study/undergraduate/courses/economics-bsc" },
      { name: "Computer Science", min_points: 96, typical_points: 112, url: "https://www.sussex.ac.uk/study/undergraduate/courses/computer-science-bsc" },
      { name: "Psychology", min_points: 96, typical_points: 112, url: "https://www.sussex.ac.uk/study/undergraduate/courses/psychology-bsc" },
      { name: "English", min_points: 88, typical_points: 104, url: "https://www.sussex.ac.uk/study/undergraduate/courses/english-literature-ba" },
      { name: "History", min_points: 88, typical_points: 104, url: "https://www.sussex.ac.uk/study/undergraduate/courses/history-ba" },
    ],
  },
  {
    name: "University of Kent",
    city: "Canterbury",
    courses: [
      { name: "Law", min_points: 104, typical_points: 120, url: "https://www.kent.ac.uk/courses/undergraduate/law/law" },
      { name: "Computer Science", min_points: 96, typical_points: 112, url: "https://www.kent.ac.uk/courses/undergraduate/computer-science/computer-science" },
      { name: "Economics", min_points: 96, typical_points: 112, url: "https://www.kent.ac.uk/courses/undergraduate/economics/economics" },
      { name: "Psychology", min_points: 88, typical_points: 104, url: "https://www.kent.ac.uk/courses/undergraduate/psychology/psychology" },
      { name: "English", min_points: 88, typical_points: 104, url: "https://www.kent.ac.uk/courses/undergraduate/english/english-and-american-literature" },
      { name: "History", min_points: 88, typical_points: 104, url: "https://www.kent.ac.uk/courses/undergraduate/history/history" },
    ],
  },
  {
    name: "Brunel University London",
    city: "London",
    courses: [
      { name: "Engineering", min_points: 96, typical_points: 112, url: "https://www.brunel.ac.uk/courses/undergraduate/mechanical-engineering-beng" },
      { name: "Computer Science", min_points: 96, typical_points: 112, url: "https://www.brunel.ac.uk/courses/undergraduate/computer-science-bsc" },
      { name: "Economics", min_points: 96, typical_points: 112, url: "https://www.brunel.ac.uk/courses/undergraduate/economics-bsc" },
      { name: "Psychology", min_points: 96, typical_points: 112, url: "https://www.brunel.ac.uk/courses/undergraduate/psychology-bsc" },
      { name: "Law", min_points: 104, typical_points: 120, url: "https://www.brunel.ac.uk/courses/undergraduate/law-llb" },
    ],
  },
  {
    name: "City, University of London",
    city: "London",
    courses: [
      { name: "Law", min_points: 120, typical_points: 136, url: "https://www.city.ac.uk/prospective-students/courses/law/undergraduate/law" },
      { name: "Computer Science", min_points: 104, typical_points: 120, url: "https://www.city.ac.uk/prospective-students/courses/engineering-and-technology/undergraduate/computer-science" },
      { name: "Economics", min_points: 104, typical_points: 120, url: "https://www.city.ac.uk/prospective-students/courses/business/undergraduate/economics" },
      { name: "Psychology", min_points: 96, typical_points: 112, url: "https://www.city.ac.uk/prospective-students/courses/health-sciences/undergraduate/psychology" },
    ],
  },
  {
    name: "University of Hertfordshire",
    city: "Hatfield",
    courses: [
      { name: "Engineering", min_points: 80, typical_points: 96, url: "https://www.herts.ac.uk/courses/undergraduate/mechanical-engineering-beng" },
      { name: "Computer Science", min_points: 80, typical_points: 96, url: "https://www.herts.ac.uk/courses/undergraduate/computer-science-bsc" },
      { name: "Psychology", min_points: 80, typical_points: 96, url: "https://www.herts.ac.uk/courses/undergraduate/psychology-bsc" },
      { name: "Law", min_points: 80, typical_points: 96, url: "https://www.herts.ac.uk/courses/undergraduate/law-llb" },
      { name: "Biology", min_points: 72, typical_points: 88, url: "https://www.herts.ac.uk/courses/undergraduate/biological-sciences-bsc" },
    ],
  },
  {
    name: "Coventry University",
    city: "Coventry",
    courses: [
      { name: "Engineering", min_points: 80, typical_points: 96, url: "https://www.coventry.ac.uk/course-structure/2025/faculty-of-engineering-environment-and-computing/undergraduate/mechanical-engineering-beng/" },
      { name: "Computer Science", min_points: 80, typical_points: 96, url: "https://www.coventry.ac.uk/course-structure/2025/faculty-of-engineering-environment-and-computing/undergraduate/computer-science-bsc/" },
      { name: "Psychology", min_points: 72, typical_points: 88, url: "https://www.coventry.ac.uk/course-structure/2025/faculty-of-health-life-sciences/undergraduate/psychology-bsc/" },
      { name: "Law", min_points: 80, typical_points: 96, url: "https://www.coventry.ac.uk/course-structure/2025/coventry-law-school/undergraduate/law-llb/" },
      { name: "Economics", min_points: 80, typical_points: 96, url: "https://www.coventry.ac.uk/course-structure/2025/coventry-business-school/undergraduate/economics-bsc/" },
    ],
  },
  {
    name: "University of Plymouth",
    city: "Plymouth",
    courses: [
      { name: "Medicine", min_points: 128, typical_points: 152, url: "https://www.plymouth.ac.uk/courses/undergraduate/bm-bs-medicine" },
      { name: "Engineering", min_points: 80, typical_points: 96, url: "https://www.plymouth.ac.uk/courses/undergraduate/beng-mechanical-engineering" },
      { name: "Computer Science", min_points: 80, typical_points: 96, url: "https://www.plymouth.ac.uk/courses/undergraduate/bsc-computer-science" },
      { name: "Psychology", min_points: 80, typical_points: 96, url: "https://www.plymouth.ac.uk/courses/undergraduate/bsc-psychology" },
      { name: "Biology", min_points: 80, typical_points: 96, url: "https://www.plymouth.ac.uk/courses/undergraduate/bsc-biology" },
    ],
  },
  {
    name: "University of Huddersfield",
    city: "Huddersfield",
    courses: [
      { name: "Engineering", min_points: 72, typical_points: 88, url: "https://courses.hud.ac.uk/2025-26/undergraduate/engineering-technology/mechanical-engineering-beng" },
      { name: "Computer Science", min_points: 72, typical_points: 88, url: "https://courses.hud.ac.uk/2025-26/undergraduate/computing-and-engineering/computer-science-bsc" },
      { name: "Psychology", min_points: 72, typical_points: 88, url: "https://courses.hud.ac.uk/2025-26/undergraduate/human-health-sciences/psychology-bsc" },
      { name: "English", min_points: 64, typical_points: 80, url: "https://courses.hud.ac.uk/2025-26/undergraduate/humanities/english-literature-ba" },
    ],
  },
  {
    name: "University of Lincoln",
    city: "Lincoln",
    courses: [
      { name: "Engineering", min_points: 80, typical_points: 96, url: "https://www.lincoln.ac.uk/course/mechengbeng/" },
      { name: "Computer Science", min_points: 80, typical_points: 96, url: "https://www.lincoln.ac.uk/course/cscbsc/" },
      { name: "Psychology", min_points: 80, typical_points: 96, url: "https://www.lincoln.ac.uk/course/psybsc/" },
      { name: "Law", min_points: 80, typical_points: 96, url: "https://www.lincoln.ac.uk/course/lawllb/" },
      { name: "Biology", min_points: 72, typical_points: 88, url: "https://www.lincoln.ac.uk/course/biobsc/" },
    ],
  },
  {
    name: "Northumbria University",
    city: "Newcastle",
    courses: [
      { name: "Law", min_points: 104, typical_points: 120, url: "https://www.northumbria.ac.uk/study-at-northumbria/courses/law-llb-uullb6/" },
      { name: "Computer Science", min_points: 88, typical_points: 104, url: "https://www.northumbria.ac.uk/study-at-northumbria/courses/computer-science-ubsccs/" },
      { name: "Engineering", min_points: 80, typical_points: 96, url: "https://www.northumbria.ac.uk/study-at-northumbria/courses/mechanical-engineering-ubengme/" },
      { name: "Psychology", min_points: 88, typical_points: 104, url: "https://www.northumbria.ac.uk/study-at-northumbria/courses/psychology-ubscpy/" },
    ],
  },
  {
    name: "University of the West of England",
    city: "Bristol",
    courses: [
      { name: "Law", min_points: 96, typical_points: 112, url: "https://www.uwe.ac.uk/courses/law/law-llb" },
      { name: "Engineering", min_points: 80, typical_points: 96, url: "https://www.uwe.ac.uk/courses/engineering/mechanical-engineering-beng" },
      { name: "Computer Science", min_points: 80, typical_points: 96, url: "https://www.uwe.ac.uk/courses/computing/computer-science-bsc" },
      { name: "Psychology", min_points: 80, typical_points: 96, url: "https://www.uwe.ac.uk/courses/health-and-applied-sciences/psychology-bsc" },
      { name: "Biology", min_points: 72, typical_points: 88, url: "https://www.uwe.ac.uk/courses/health-and-applied-sciences/biological-sciences-bsc" },
    ],
  },
  {
    name: "University of Portsmouth",
    city: "Portsmouth",
    courses: [
      { name: "Law", min_points: 96, typical_points: 112, url: "https://www.port.ac.uk/study/courses/undergraduate/law-llb" },
      { name: "Computer Science", min_points: 80, typical_points: 96, url: "https://www.port.ac.uk/study/courses/undergraduate/computer-science-bsc" },
      { name: "Engineering", min_points: 72, typical_points: 88, url: "https://www.port.ac.uk/study/courses/undergraduate/mechanical-and-design-engineering-beng" },
      { name: "Psychology", min_points: 80, typical_points: 96, url: "https://www.port.ac.uk/study/courses/undergraduate/psychology-bsc" },
      { name: "Biology", min_points: 72, typical_points: 88, url: "https://www.port.ac.uk/study/courses/undergraduate/biology-bsc" },
    ],
  },
  {
    name: "University of Wolverhampton",
    city: "Wolverhampton",
    courses: [
      { name: "Engineering", min_points: 64, typical_points: 80, url: "https://www.wlv.ac.uk/courses/course-details/course/engineering-beng/" },
      { name: "Computer Science", min_points: 64, typical_points: 80, url: "https://www.wlv.ac.uk/courses/course-details/course/computer-science-bsc/" },
      { name: "Psychology", min_points: 64, typical_points: 80, url: "https://www.wlv.ac.uk/courses/course-details/course/psychology-bsc/" },
      { name: "Law", min_points: 64, typical_points: 80, url: "https://www.wlv.ac.uk/courses/course-details/course/law-llb/" },
    ],
  },
  {
    name: "De Montfort University",
    city: "Leicester",
    courses: [
      { name: "Law", min_points: 80, typical_points: 96, url: "https://www.dmu.ac.uk/study/courses/undergraduate-courses/law-llb-degree/" },
      { name: "Computer Science", min_points: 72, typical_points: 88, url: "https://www.dmu.ac.uk/study/courses/undergraduate-courses/computer-science-bsc/" },
      { name: "Engineering", min_points: 64, typical_points: 80, url: "https://www.dmu.ac.uk/study/courses/undergraduate-courses/engineering-beng/" },
      { name: "Psychology", min_points: 72, typical_points: 88, url: "https://www.dmu.ac.uk/study/courses/undergraduate-courses/psychology-bsc/" },
    ],
  },
  {
    name: "Anglia Ruskin University",
    city: "Cambridge",
    courses: [
      { name: "Medicine", min_points: 104, typical_points: 120, url: "https://aru.ac.uk/study/undergraduate/medicine-mbbs" },
      { name: "Law", min_points: 72, typical_points: 88, url: "https://aru.ac.uk/study/undergraduate/law" },
      { name: "Computer Science", min_points: 64, typical_points: 80, url: "https://aru.ac.uk/study/undergraduate/computer-science" },
      { name: "Psychology", min_points: 72, typical_points: 88, url: "https://aru.ac.uk/study/undergraduate/psychology-bsc" },
      { name: "Biology", min_points: 64, typical_points: 80, url: "https://aru.ac.uk/study/undergraduate/biology-bsc" },
    ],
  },
  {
    name: "University of Salford",
    city: "Salford",
    courses: [
      { name: "Engineering", min_points: 72, typical_points: 88, url: "https://www.salford.ac.uk/courses/undergraduate/mechanical-engineering" },
      { name: "Computer Science", min_points: 72, typical_points: 88, url: "https://www.salford.ac.uk/courses/undergraduate/computer-science" },
      { name: "Psychology", min_points: 72, typical_points: 88, url: "https://www.salford.ac.uk/courses/undergraduate/psychology" },
      { name: "English", min_points: 64, typical_points: 80, url: "https://www.salford.ac.uk/courses/undergraduate/english" },
    ],
  },
  {
    name: "University of Bradford",
    city: "Bradford",
    courses: [
      { name: "Medicine", min_points: 112, typical_points: 128, url: "https://www.bradford.ac.uk/courses/ug/medicine-bmbs/" },
      { name: "Engineering", min_points: 64, typical_points: 80, url: "https://www.bradford.ac.uk/courses/ug/mechanical-engineering-beng/" },
      { name: "Computer Science", min_points: 64, typical_points: 80, url: "https://www.bradford.ac.uk/courses/ug/computer-science-bsc/" },
      { name: "Psychology", min_points: 64, typical_points: 80, url: "https://www.bradford.ac.uk/courses/ug/psychology-bsc/" },
    ],
  },
  {
    name: "University of Greenwich",
    city: "London",
    courses: [
      { name: "Law", min_points: 80, typical_points: 96, url: "https://www.gre.ac.uk/ug-programmes/law/llb-law" },
      { name: "Computer Science", min_points: 64, typical_points: 80, url: "https://www.gre.ac.uk/ug-programmes/computing-maths/bsc-computer-science" },
      { name: "Engineering", min_points: 64, typical_points: 80, url: "https://www.gre.ac.uk/ug-programmes/engineering/beng-mechanical-engineering" },
      { name: "Psychology", min_points: 72, typical_points: 88, url: "https://www.gre.ac.uk/ug-programmes/education-health/bsc-psychology" },
    ],
  },
  {
    name: "London Metropolitan University",
    city: "London",
    courses: [
      { name: "Law", min_points: 64, typical_points: 80, url: "https://www.londonmet.ac.uk/courses/undergraduate/law-llb/" },
      { name: "Computer Science", min_points: 48, typical_points: 64, url: "https://www.londonmet.ac.uk/courses/undergraduate/computer-science-bsc/" },
      { name: "Psychology", min_points: 48, typical_points: 64, url: "https://www.londonmet.ac.uk/courses/undergraduate/psychology-bsc/" },
      { name: "Biology", min_points: 48, typical_points: 64, url: "https://www.londonmet.ac.uk/courses/undergraduate/biomedical-science-bsc/" },
    ],
  },
  {
    name: "Staffordshire University",
    city: "Stoke-on-Trent",
    courses: [
      { name: "Computer Science", min_points: 64, typical_points: 80, url: "https://www.staffs.ac.uk/course/computer-science-bsc" },
      { name: "Engineering", min_points: 64, typical_points: 80, url: "https://www.staffs.ac.uk/course/mechanical-engineering-beng" },
      { name: "Psychology", min_points: 64, typical_points: 80, url: "https://www.staffs.ac.uk/course/psychology-bsc" },
      { name: "Law", min_points: 64, typical_points: 80, url: "https://www.staffs.ac.uk/course/law-llb" },
    ],
  },
  {
    name: "University of Central Lancashire",
    city: "Preston",
    courses: [
      { name: "Medicine", min_points: 104, typical_points: 120, url: "https://www.uclan.ac.uk/courses/undergraduate/medicine_mbbs_primary_qualification" },
      { name: "Law", min_points: 80, typical_points: 96, url: "https://www.uclan.ac.uk/courses/undergraduate/law_llb" },
      { name: "Engineering", min_points: 64, typical_points: 80, url: "https://www.uclan.ac.uk/courses/undergraduate/mechanical_engineering_beng" },
      { name: "Computer Science", min_points: 64, typical_points: 80, url: "https://www.uclan.ac.uk/courses/undergraduate/computer_science_bsc_honours" },
      { name: "Psychology", min_points: 64, typical_points: 80, url: "https://www.uclan.ac.uk/courses/undergraduate/psychology_bsc_honours" },
    ],
  },
  {
    name: "University of Sunderland",
    city: "Sunderland",
    courses: [
      { name: "Computer Science", min_points: 48, typical_points: 64, url: "https://www.sunderland.ac.uk/study/computing/computer-science-bsc/" },
      { name: "Engineering", min_points: 48, typical_points: 64, url: "https://www.sunderland.ac.uk/study/engineering/engineering-beng/" },
      { name: "Psychology", min_points: 48, typical_points: 64, url: "https://www.sunderland.ac.uk/study/psychology/psychology-bsc/" },
      { name: "Law", min_points: 64, typical_points: 80, url: "https://www.sunderland.ac.uk/study/law/law-llb/" },
    ],
  },
  {
    name: "University of Derby",
    city: "Derby",
    courses: [
      { name: "Computer Science", min_points: 64, typical_points: 80, url: "https://www.derby.ac.uk/undergraduate/computing-courses/computer-science-bsc-hons/" },
      { name: "Engineering", min_points: 64, typical_points: 80, url: "https://www.derby.ac.uk/undergraduate/engineering-courses/mechanical-engineering-beng-hons/" },
      { name: "Psychology", min_points: 64, typical_points: 80, url: "https://www.derby.ac.uk/undergraduate/psychology-courses/psychology-bsc-hons/" },
      { name: "Law", min_points: 64, typical_points: 80, url: "https://www.derby.ac.uk/undergraduate/law-courses/law-llb-hons/" },
      { name: "Biology", min_points: 56, typical_points: 72, url: "https://www.derby.ac.uk/undergraduate/biology-courses/biological-sciences-bsc-hons/" },
    ],
  },
  {
    name: "University of Winchester",
    city: "Winchester",
    courses: [
      { name: "English", min_points: 88, typical_points: 104, url: "https://www.winchester.ac.uk/courses/undergraduate/english-ba-hons/" },
      { name: "History", min_points: 80, typical_points: 96, url: "https://www.winchester.ac.uk/courses/undergraduate/history-ba-hons/" },
      { name: "Psychology", min_points: 80, typical_points: 96, url: "https://www.winchester.ac.uk/courses/undergraduate/psychology-bsc-hons/" },
      { name: "Law", min_points: 80, typical_points: 96, url: "https://www.winchester.ac.uk/courses/undergraduate/law-llb-hons/" },
    ],
  },
  {
    name: "Keele University",
    city: "Keele",
    courses: [
      { name: "Medicine", min_points: 136, typical_points: 160, url: "https://www.keele.ac.uk/study/undergraduate/medicine/medicine/" },
      { name: "Law", min_points: 104, typical_points: 120, url: "https://www.keele.ac.uk/study/undergraduate/law/law/" },
      { name: "Computer Science", min_points: 96, typical_points: 112, url: "https://www.keele.ac.uk/study/undergraduate/computing/computerscience/" },
      { name: "Psychology", min_points: 96, typical_points: 112, url: "https://www.keele.ac.uk/study/undergraduate/psychology/psychology/" },
      { name: "Biology", min_points: 96, typical_points: 112, url: "https://www.keele.ac.uk/study/undergraduate/lifesciences/biology/" },
      { name: "Chemistry", min_points: 96, typical_points: 112, url: "https://www.keele.ac.uk/study/undergraduate/chemistry/chemistry/" },
    ],
  },
  {
    name: "Aston University",
    city: "Birmingham",
    courses: [
      { name: "Engineering", min_points: 120, typical_points: 136, url: "https://www.aston.ac.uk/study/courses/mechanical-engineering-beng" },
      { name: "Computer Science", min_points: 120, typical_points: 136, url: "https://www.aston.ac.uk/study/courses/computer-science-bsc" },
      { name: "Economics", min_points: 120, typical_points: 136, url: "https://www.aston.ac.uk/study/courses/economics-bsc" },
      { name: "Psychology", min_points: 112, typical_points: 128, url: "https://www.aston.ac.uk/study/courses/psychology-bsc" },
    ],
  },
  {
    name: "Edge Hill University",
    city: "Ormskirk",
    courses: [
      { name: "Medicine", min_points: 112, typical_points: 128, url: "https://www.edgehill.ac.uk/departments/faculty-of-health/medicine/" },
      { name: "Computer Science", min_points: 72, typical_points: 88, url: "https://www.edgehill.ac.uk/departments/faculty-of-arts-and-sciences/computer-science/" },
      { name: "Psychology", min_points: 80, typical_points: 96, url: "https://www.edgehill.ac.uk/departments/faculty-of-health/psychology/" },
      { name: "English", min_points: 72, typical_points: 88, url: "https://www.edgehill.ac.uk/departments/faculty-of-arts-and-sciences/english/" },
      { name: "History", min_points: 72, typical_points: 88, url: "https://www.edgehill.ac.uk/departments/faculty-of-arts-and-sciences/history/" },
    ],
  },
  {
    name: "University of Stirling",
    city: "Stirling",
    courses: [
      { name: "Economics", min_points: 104, typical_points: 120, url: "https://www.stir.ac.uk/courses/ug/economics/" },
      { name: "Psychology", min_points: 96, typical_points: 112, url: "https://www.stir.ac.uk/courses/ug/psychology/" },
      { name: "English", min_points: 88, typical_points: 104, url: "https://www.stir.ac.uk/courses/ug/english/" },
      { name: "History", min_points: 88, typical_points: 104, url: "https://www.stir.ac.uk/courses/ug/history/" },
      { name: "Biology", min_points: 96, typical_points: 112, url: "https://www.stir.ac.uk/courses/ug/biology/" },
    ],
  },
  {
    name: "Heriot-Watt University",
    city: "Edinburgh",
    courses: [
      { name: "Engineering", min_points: 120, typical_points: 136, url: "https://www.hw.ac.uk/study/uk/undergraduate/mechanical-engineering.htm" },
      { name: "Computer Science", min_points: 120, typical_points: 136, url: "https://www.hw.ac.uk/study/uk/undergraduate/computer-science.htm" },
      { name: "Economics", min_points: 104, typical_points: 120, url: "https://www.hw.ac.uk/study/uk/undergraduate/economics.htm" },
      { name: "Chemistry", min_points: 104, typical_points: 120, url: "https://www.hw.ac.uk/study/uk/undergraduate/chemistry.htm" },
    ],
  },
  {
    name: "Robert Gordon University",
    city: "Aberdeen",
    courses: [
      { name: "Engineering", min_points: 96, typical_points: 112, url: "https://www.rgu.ac.uk/study/courses/undergraduate/mechanical-and-offshore-engineering-beng" },
      { name: "Computer Science", min_points: 88, typical_points: 104, url: "https://www.rgu.ac.uk/study/courses/undergraduate/computing-bsc" },
      { name: "Psychology", min_points: 80, typical_points: 96, url: "https://www.rgu.ac.uk/study/courses/undergraduate/psychology-bsc" },
    ],
  },
  {
    name: "University of the Arts London",
    city: "London",
    courses: [
      { name: "English", min_points: 88, typical_points: 104, url: "https://www.arts.ac.uk/colleges/london-college-of-communication/undergraduate" },
    ],
  },
  {
    name: "University of Hull",
    city: "Hull",
    courses: [
      { name: "Law", min_points: 96, typical_points: 112, url: "https://www.hull.ac.uk/choose-hull/study-at-hull/courses/law-llb.aspx" },
      { name: "Computer Science", min_points: 80, typical_points: 96, url: "https://www.hull.ac.uk/choose-hull/study-at-hull/courses/computer-science-bsc.aspx" },
      { name: "Engineering", min_points: 80, typical_points: 96, url: "https://www.hull.ac.uk/choose-hull/study-at-hull/courses/mechanical-engineering-beng.aspx" },
      { name: "Psychology", min_points: 80, typical_points: 96, url: "https://www.hull.ac.uk/choose-hull/study-at-hull/courses/psychology-bsc.aspx" },
      { name: "History", min_points: 72, typical_points: 88, url: "https://www.hull.ac.uk/choose-hull/study-at-hull/courses/history-ba.aspx" },
      { name: "Biology", min_points: 80, typical_points: 96, url: "https://www.hull.ac.uk/choose-hull/study-at-hull/courses/biology-bsc.aspx" },
    ],
  },
];
